### ISSUE TITLE
Refactor MergeSprites to use the params keyword

### ISSUE THREAD

**Issue by ender-titan1** [ender-titan1/moondown-metroidvania#21]
Refactor Extensions.MergeSprites to look like this:

```
MergeSprites(this Sprite main, params Sprite[] overlay)
```

Please adjust the behaviour of the method to have the desired effect and change all the calls to match the new parameters. Also change the contents of the summary block.

**Comment by RishiKumarRay** [comment]
Do we have to change all the lines where this is present? to this line MergeSprites(this Sprite main, params Sprite[] overlay)

**Comment by ender-titan1** [comment]
In Item.cs and Weapon.cs you will find something like this:
```
sprite = new Sprite[] { ... }.MergeSprites();
```

After editing the method the new line should look like this:

```
sprite = sprite1.MergeSprites(sprite2)
```

**Comment by RishiKumarRay** [comment]
Assign me

**Comment by RishiKumarRay** [comment]
@ender-titan1  please review the PR #22
